icorp_h=$(SRC)/icorp.h $(ENGINEINC)/build.h $(ENGINEINC)/pragmas.h $(ENGINEINC)/cache1d.h $(ENGINEINC)/baselayer.h $(ENGINEINC)/mmulti.h $(SRC)/names.h $(SRC)/sndmod.h $(SRC)/les.h $(SRC)/jeff.h $(SRC)/raf.h $(SRC)/whdefs.h $(SRC)/keydefs.h

$(SRC)/b5compat.$o: $(SRC)/b5compat.c $(ENGINEINC)/build.h
$(SRC)/config.$o: $(SRC)/config.c $(ENGINEINC)/compat.h $(ENGINEINC)/osd.h $(ENGINEINC)/scriptfile.h $(ENGINEINC)/baselayer.h $(icorp_h)
$(SRC)/whani.$o: $(SRC)/whani.c $(icorp_h)
$(SRC)/whaven.$o: $(SRC)/whaven.c $(icorp_h) $(ENGINEINC)/osd.h $(ENGINEINC)/startwin.h $(SRC)/version.h
$(SRC)/whfx.$o: $(SRC)/whfx.c $(icorp_h)
$(SRC)/whinp.$o: $(SRC)/whinp.c $(icorp_h) $(SRC)/keydefs.h
$(SRC)/whmenu.$o: $(SRC)/whmenu.c $(ENGINEINC)/osd.h $(icorp_h)
$(SRC)/whnet.$o: $(SRC)/whnet.c $(icorp_h) $(ENGINEINC)/mmulti.h
$(SRC)/whobj.$o: $(SRC)/whobj.c $(icorp_h)
$(SRC)/whplr.$o: $(SRC)/whplr.c $(icorp_h)
$(SRC)/whsmk.$o: $(SRC)/whsmk.c $(icorp_h) $(AUDIOLIBROOT)/include/fx_man.h
$(SRC)/whsndmod.$o: $(SRC)/whsndmod.c $(icorp_h) $(AUDIOLIBROOT)/include/fx_man.h
$(SRC)/whtag.$o: $(SRC)/whtag.c $(icorp_h)
$(SRC)/version.$o: $(SRC)/version.c
$(SRC)/version-auto.$o: $(SRC)/version-auto.c
$(LIBSMACKERSRC)/smacker.$o: $(LIBSMACKERSRC)/smacker.c

$(SRC)/whbuild.$o: $(SRC)/whbuild.c $(build_h) $(ENGINEINC)/editor.h $(ENGINEINC)/pragmas.h $(ENGINEINC)/baselayer.h $(ENGINEINC)/cache1d.h $(SRC)/names.h

# Derived source files from art assets
$(RSRC)/build_bmp.$o: $(RSRC)/build_bmp.c
$(RSRC)/build_bmp.c: $(RSRC)/build.bmp
$(RSRC)/build_startwin_gtk_gresource.c $(RSRC)/build_startwin_gtk_gresource.h: $(RSRC)/build_startwin_gtk.gresource.xml $(RSRC)/build.png $(ENGINERSRC)/startwin_gtk.glade $(RSRC)/build_startwin_gtk_appname.txt $(RSRC)/startwin_gtk_website.txt $(RSRC)/startwin_gtk_version.txt
$(RSRC)/game_bmp.$o: $(RSRC)/game_bmp.c
$(RSRC)/game_bmp.c: $(RSRC)/game.bmp
$(RSRC)/game_startwin_gtk_gresource.c $(RSRC)/game_startwin_gtk_gresource.h: $(RSRC)/game_startwin_gtk.gresource.xml $(RSRC)/game.png $(ENGINERSRC)/startwin_gtk.glade $(RSRC)/game_startwin_gtk_appname.txt $(RSRC)/startwin_gtk_website.txt $(RSRC)/startwin_gtk_version.txt

$(SRC)/gameres.$(res): $(SRC)/gameres.rc $(ENGINEINC)/startwin_win.rc $(ENGINEINC)/startwin_win.h $(RSRC)/startwin_game.bmp $(RSRC)/game_icon.ico $(RSRC)/game.manifest
$(SRC)/buildres.$(res): $(SRC)/buildres.rc $(ENGINEINC)/startwin_win.rc $(ENGINEINC)/startwin_win.h $(RSRC)/startwin_build.bmp $(RSRC)/build_icon.ico $(RSRC)/build.manifest

